trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: GCP-Auth  # Your variable group containing GCP_SA_KEY

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-441.0.0-linux-x86_64.tar.gz
    tar -xf google-cloud-sdk-*.tar.gz
    ./google-cloud-sdk/install.sh --quiet
    source ./google-cloud-sdk/path.bash.inc
  displayName: 'Install Google Cloud SDK'

- script: |
    echo "$GCP_SA_KEY" > gcp-key.json
    gcloud auth activate-service-account --key-file=gcp-key.json
    gcloud config set project versatile-hash-470105-k0
    gcloud container clusters get-credentials brickmaster-cluster --zone asia-south1-a
  displayName: 'Authenticate to GCP'
  env:
    GCP_SA_KEY: $(GCP_SA_KEY)

- script: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml
  displayName: 'Install NGINX Ingress Controller'

- script: |
    kubectl create namespace cert-manager || true
    helm repo add jetstack https://charts.jetstack.io
    helm repo update
    helm install cert-manager jetstack/cert-manager --namespace cert-manager --set installCRDs=true
  displayName: 'Install cert-manager'

- script: |
    kubectl apply -f kubernetes/clusterissuer.yaml
    kubectl create namespace viktest || true
    kubectl apply -f kubernetes/postgres-secret.yaml -n viktest
    kubectl apply -f kubernetes/configmap.yaml -n viktest
    kubectl apply -f kubernetes/postgres-deployment.yaml -n viktest
    kubectl apply -f kubernetes/deployment.yaml -n viktest
    kubectl apply -f kubernetes/ingress.yaml -n viktest
    kubectl apply -f kubernetes/certificate.yaml -n viktest
  displayName: 'Apply Kubernetes Manifests'

- script: |
    kubectl get pods -n viktest
    kubectl get ingress -n viktest
    kubectl describe certificate brickmaster-tls -n viktest
    kubectl get certificaterequest -n viktest
  displayName: 'Verify Deployment'