version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=C-Square
      - POSTGRES_USER=C-Square
      - POSTGRES_PASSWORD=Vikky98480
      - EMAIL_USER=csquare.co.in@gmail.com
      - EMAIL_PASS=kpor bdfw wvgi clta
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=C-Square
      - POSTGRES_USER=C-Square
      - POSTGRES_PASSWORD=Vikky98480
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U C-Square"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: