trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'your-acr-name'
  acrResourceGroup: 'your-resource-group'
  aksClusterName: 'your-aks-cluster'
  aksResourceGroup: 'your-resource-group'
  imageRepository: 'brickmaster-website'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        containerRegistry: $(acrName)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to Kubernetes
    steps:
    - task: AzureCLI@2
      displayName: Set AKS context
      inputs:
        azureSubscription: 'Your-Azure-Subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName)
          
    - task: KubernetesManifest@0
      displayName: Deploy to Kubernetes cluster
      inputs:
        action: 'deploy'
        manifests: |
          $(Build.SourcesDirectory)/kubernetes/deployment.yaml
          $(Build.SourcesDirectory)/kubernetes/configmap.yaml
        containers: '$(acrName).azurecr.io/$(imageRepository):$(tag)'