apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  host: cG9zdGdyZXMudmlrdGVzdC5zdmMuY2x1c3Rlci5sb2NhbA==  # Base64-encoded "postgres.viktest.svc.cluster.local"
  port: NTQzMg==  # Base64-encoded "5432"
  database: YnJpY2ttYXN0ZXI=  # Base64-encoded "brickmaster"
  username: YnJpY2ttYXN0ZXI=  # Base64-encoded "brickmaster"
  password: Vmlra3k5ODQ4MA==  # Base64-encoded "Vikky98480"