apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  host: cG9zdGdyZXMudmlrdGVzdC5zdmMuY2x1c3Rlci5sb2NhbA==  # Base64-encoded "postgres.viktest.svc.cluster.local"
  port: NTQzMg==                                       # Base64-encoded "5432"
  database: YnJpY2ttYXN0ZXI=                            # Base64-encoded "brickmaster"
  username: YnJpY2ttYXN0ZXI=                            # Base64-encoded "brickmaster"
  password: Vmlra3k5ODQ4MA==                            # Base64-encoded "Vikky98480"

---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:
  email_user: Y3NxdWFyZS5jby5pbkBnbWFpbC5jb20=          # Base64-encoded "csquare.co.in@gmail.com"
  email_pass: a3BvciBiZGZ3IHd2Z2kgY2x0YQ==              # Base64-encoded "kpor bdfw wvgi clta"

---
apiVersion: v1
kind: Secret
metadata:
  name: google-secret
type: Opaque
data:
  google_client_id: MzQ1MTk3MzYwNjk1LXBodWUwanBmOTlqZ2Ewb2ZoNWk3OGd0aDRxYWg5cW4yLmFwcHMuZ29vZ2xlY3VzdGVyYXRpb24uY29t
  # Base64-encoded "345197360695-phue0j0f99jga0ofh5i78gth4qah9qn2.apps.googleusercontent.com"
  google_client_secret: R09DU1BYLTgtTDNMeHByR29lenNOMnQzbENnVmpwU2ctWUpvWA==
  # Base64-encoded "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"